title: OCI API Serverless
description: >-
  This course introduces the OCI Application Gateway, OCI Function and Oracle
  Autonomous Database. 
template:
  repo: oci-api-serverless-template
  name: oci-api-serverless
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
